#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + '/src'
require 'schema'

puts "Generating schema for #{ARGV[0]}"
schema = Schema.new File.read(ARGV[0])
doc = schema.generate_xsd
out = ARGV[1] || "#{File.basename(ARGV[0], '.msd')}_#{schema.version}.xsd"
puts "\tWriting schema document: #{out}"
File.open(out, 'w') { |f| doc.write(f, 2) }
