#!/usr/bin/env ruby

$: << 'src'
require 'src/schema'

schema = Schema.new File.read(ARGV[0])
doc = schema.generate_xsd
out = ARGV[1] || "#{File.basename(ARGV[0], '.msd')}_#{schema.version}.xsd"
File.open(out, 'w') { |f| doc.write(f, 2) }
