#!/usr/bin/env ruby

$: << File.dirname(__FILE__) + '/src'
require 'schema'
require 'latex_parser'

Glossary = LatexParser.new
path = File.expand_path('mtc-terms.tex', '.')
puts "Loading Glossary: #{File.basename(path)}"
Glossary.parse_glossary(path)

ARGV.each do |file|
  puts "Parsing schema for #{file}"
  schema = Schema.new File.read(file)

  %w{1.0 1.1}.each do |version|
    puts "  Generating schema for #{file} #{version}"
    doc = schema.generate_xsd(version)
    ver = "_#{version}" if version != '1.1'
    out = "#{File.basename(file, '.msd')}_#{schema.version}#{ver}.xsd"
    puts "    Writing schema document: #{out}"
    File.open(out, 'w') { |f| doc.write(f, 2) }
  end
end
